APP_VERSION = "1.0.0"

WINDOW_NAME = "PyGame Template"
WINDOW_INIT_WIDTH = 800
WINDOW_INIT_HEIGHT = 750

FONT_PATH = "font/SourceSansPro-SemiBoldItalic.ttf"
FONT_SIZE = 20

MAX_FPS = 2000

PLAYER_SPEED = 500
PLAYER_COLOR = (255, 255, 255)

PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50

PLAYER_INIT_X = WINDOW_INIT_WIDTH / 2 - PLAYER_WIDTH / 2
PLAYER_INIT_Y = WINDOW_INIT_HEIGHT / 2 - PLAYER_HEIGHT / 2

COLOR_BACKGROUND = (0, 0, 0)
COLOR_FONT = (255, 255, 255)
